# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8f69f79cb352f40204a743cba3358a5e4bfb0ef8e4462cbeb8d31d43ab6d92cad262c099efe0c496a4b7af0a273621049f38845f706e1a4a553e005e121299c

test:
  secret_key_base: 34946b6f75308d52eb4254888184e19f985a86a365bf3b20a3a4c4a63d0a710efe6d4bff1f32955f85d27c7b471fc3ab5a4228cd2a134ecf7dd007d6c95a5000

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
